[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules"]
remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@ensdomains/=node_modules/@ensdomains/",
    "@eth-optimism/=node_modules/@eth-optimism/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@prb/=node_modules/@prb/",
    "hardhat/=node_modules/hardhat/",
    "solidity-bytes-utils/=node_modules/solidity-bytes-utils/",
    "forge-std/=node_modules/forge-std/src/",
]
test = 'test/foundry'
cache_path  = 'forge-cache'

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[invariant]
runs = 20
depth = 25
fail_on_revert = true
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
