name: CI
on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  ci:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Yarn dependencies
        run: yarn install

      - name: Run solhint
        run: yarn solhint

      - name: Run prettier
        run: yarn prettier

      - name: Hardhat clean
        run: npx hardhat clean

      - name: Compile contracts
        run: yarn compile

      - name: Run tests
        env:
            ETHEREUM_RPC_URL: ${{ secrets.ETHEREUM_RPC_URL }}
        run: |
          yarn test
          forge test --no-match-test testFork -vvv --ffi
